import type { TopicData } from './types';

export const topic3Data: TopicData = {
  id: "u1t3",
  title: "EMS and NMS Architecture",
  moduleName: "Unit I: Introduction to Network Management and Frameworks",
  context: {
    prerequisites: ["eTOM and TMN Framework", "Understanding of Mobile Network"],
    dependentTopics: ["FCAPS Process", "NMS SBI and NBI"],
    nextSteps: "Learn about the FCAPS management framework that defines what functions EMS and NMS must implement."
  },
  storytelling: {
    analogy: "A Hospital's Department Structure",
    story: "An EMS (Element Management System) is like a hospital department — it manages all the specialised equipment within one ward. For example, the Cardiology department (Ericsson EMS) manages all cardiac monitors and ECG machines (4G base stations). The Radiology department (Nokia EMS) manages all MRI and X-ray machines (5G gNBs). The hospital's central administration (NMS) doesn't interact directly with individual machines — it receives department-level reports and coordinates across all wards. When an MRI machine fails (network element fault), Radiology raises an alert to hospital administration, which orchestrates a response: notifying the on-call engineer, logging the incident, and tracking resolution. The NMS sees the whole hospital; the EMS only sees its ward. This separation is intentional — hospital administration cannot be expected to understand the clinical specifics of every machine, just as an NMS cannot hold vendor-specific knowledge for every network element type. Vendor-specific expertise lives in the EMS layer.",
    reflectiveQuestions: [
      "Why is it better to have domain-specific EMS systems rather than one monolithic NMS that manages everything directly?",
      "How does an NMS aggregate alarms from multiple EMS systems without being overwhelmed by raw event volume?",
      "What happens to NMS visibility and service assurance when one of its upstream EMS systems goes offline?"
    ],
    technicalConnection: "EMS manages a single-vendor or single-technology domain via the TMN Element Layer using the Q3 interface (SNMP/NETCONF/vendor proprietary). NMS sits above multiple EMSs at the TMN Network Management Layer, providing an end-to-end cross-domain network view. The NBI (Northbound Interface) exposes NMS data upward to OSS/BSS systems (typically REST APIs, SOAP, or CORBA/XML). The SBI (Southbound Interface) connects NMS downward to EMS layers, and EMS downward to NEs. Alarm correlation, root-cause analysis, and topology aggregation all happen at the NMS layer."
  },
  mathModelling: {
    need: "To quantify the alarm aggregation ratio — determining how effectively the NMS compresses raw alarm volume from multiple EMS domains into actionable root-cause alarms.",
    equation: "R_{\\text{agg}} = \\frac{\\displaystyle\\sum_{i=1}^{k} A_i}{A_{\\text{nms}}}",
    technicalDetails: "\\( R_{\\text{agg}} \\) is the alarm aggregation ratio at the NMS. \\( A_i \\) is the number of raw alarms generated by EMS domain \\( i \\) during a given observation window. \\( k \\) is the total number of EMS domains managed by the NMS. \\( A_{\\text{nms}} \\) is the number of correlated (root-cause) alarms presented to the operator at the NMS after applying alarm correlation and de-duplication rules. A higher \\( R_{\\text{agg}} \\) indicates better alarm compression — for example, a ratio of 10 means the operator sees 1 actionable alarm for every 10 raw events. Industry targets typically aim for \\( R_{\\text{agg}} \\geq 5 \\) to prevent alarm fatigue.",
    explanation: [
      { term: "R_{\\text{agg}}", meaning: "Alarm aggregation ratio — raw alarms divided by correlated alarms at NMS" },
      { term: "A_i", meaning: "Number of raw alarms generated by EMS domain i in an observation window" },
      { term: "k", meaning: "Total number of EMS domains managed by the NMS" },
      { term: "A_{\\text{nms}}", meaning: "Number of correlated root-cause alarms presented at the NMS level" }
    ],
    advantages: [
      "Reduces operator alarm fatigue by presenting only root-cause alarms rather than cascaded symptom alarms",
      "Enables faster root-cause identification by grouping topologically related alarms into single incidents"
    ],
    limitations: [
      "Alarm correlation logic is rule-based and may miss novel failure patterns not previously encountered",
      "Excessively high aggregation ratios can mask secondary faults that share a correlated root-cause alarm"
    ],
    simulation: {
      description: "Adjust the number of EMS domains and alarms per domain to see how the aggregation ratio at the NMS changes. The NMS correlates approximately 15% of total alarms into root-cause alarms. The plot shows aggregation ratio as domain count increases from 1 to the selected maximum.",
      parameters: [
        { id: "domains", name: "EMS Domains", min: 1, max: 10, default: 4, step: 1, unit: "" },
        { id: "alarmsPerDomain", name: "Alarms per Domain", min: 10, max: 200, default: 50, step: 10, unit: "" }
      ],
      generateData: (params) => {
        const maxDomains = params.domains || 4;
        const alarmsPerDomain = params.alarmsPerDomain || 50;
        const pts: Array<{ x: number; y: number }> = [];
        for (let x = 1; x <= maxDomains; x++) {
          const total = x * alarmsPerDomain;
          const correlated = Math.ceil(total * 0.15);
          const ratio = total / correlated;
          pts.push({ x, y: parseFloat(ratio.toFixed(2)) });
        }
        return pts;
      },
      labels: { x: "EMS Domains", y: "Aggregation Ratio" }
    }
  },
  activities: {
    level1: "Define the following management systems and draw the four-tier management hierarchy diagram: NE (Network Element), EMS (Element Management System), NMS (Network Management System), OSS (Operations Support System), BSS (Business Support System). Label the interfaces between each tier.",
    level2: "Explain the role of the Northbound Interface (NBI) and Southbound Interface (SBI) in NMS architecture. For each interface, state: (a) which systems it connects, (b) the protocols commonly used (REST, SNMP, NETCONF, CORBA), and (c) what data flows across it.",
    level3: "Given 5 EMS domains each generating 80 raw alarms in a 15-minute window, and the NMS correlates these into 60 root-cause alarms, calculate R_agg. Interpret the result: is this a good aggregation ratio?",
    level4: "Research a commercial NMS product — Nokia NetAct, Ericsson ENM (Evolved Network Manager), or Huawei U2000 — and document its architecture. Identify: how many EMS domains it supports, what NBIs it exposes, and how it implements alarm correlation."
  },
  projects: {
    scope: "Design a complete NMS architecture for a hypothetical multi-vendor mobile operator with three technology domains: 4G LTE (Ericsson RAN), 5G NR (Nokia RAN), and Microwave Transport (Huawei).",
    objectives: [
      "Define the EMS system for each domain, specify their vendor protocols (Q3/SNMP/NETCONF), and draw all interface connections",
      "Design the NMS alarm aggregation pipeline: raw alarm ingestion, de-duplication, correlation engine, and root-cause alarm presentation",
      "Specify three NBI API endpoints that the NMS exposes to the OSS for alarm retrieval, performance data collection, and configuration push"
    ],
    deliverables: [
      "Architecture diagram showing all NEs, EMS systems, NMS, OSS/BSS with labeled interfaces (SBI, Q3, NBI, X)",
      "Alarm aggregation calculation table showing raw alarm counts per domain, total, correlated count, and R_agg",
      "API specification document defining 3 NBI REST endpoints (URL, method, request/response schema, authentication)"
    ]
  },
  questions: [
    {
      q: "What is the key architectural difference between an EMS and an NMS?",
      a: "An EMS (Element Management System) manages a single-vendor or single-technology domain. It uses vendor-specific protocols (proprietary CLI, SNMP MIBs, NETCONF YANG models) to communicate directly with network elements via the Q3 interface. It has deep, vendor-specific knowledge of each element type. An NMS (Network Management System) sits one layer above, managing multiple EMS domains. It receives normalised, vendor-agnostic events from each EMS and provides a cross-domain, end-to-end network view. The NMS does not communicate directly with NEs — it relies on EMS for element-level data and adds correlation, topology aggregation, and service-level visibility that no single EMS can provide alone.",
      type: "Conceptual"
    },
    {
      q: "What interfaces connect EMS to NMS (SBI) and NMS to OSS/BSS (NBI), and what protocols are typically used?",
      a: "The Southbound Interface (SBI) connects the NMS downward to EMS systems. It commonly uses SNMP (trap forwarding, polling), NETCONF/YANG (configuration and state), CORBA/CMIP (legacy TMN Q3 implementations), or vendor REST APIs. The Northbound Interface (NBI) connects the NMS upward to OSS/BSS platforms. It typically exposes REST/HTTP APIs (JSON/XML), SOAP/XML Web Services, or 3GPP-defined interfaces (Itf-N for 3GPP OSS). The NBI is the integration point for service assurance platforms, ticketing systems (ServiceNow), and analytics engines.",
      type: "Conceptual"
    },
    {
      q: "Calculate R_agg given 4 EMS domains each generating 60 raw alarms, and the NMS correlates these into 48 root-cause alarms.",
      a: "Total raw alarms = 4 × 60 = 240. Correlated alarms at NMS = 48. R_agg = 240 / 48 = 5.0. An aggregation ratio of 5 means the operator sees 1 actionable alarm for every 5 raw events — a reasonable level of alarm compression. To further improve this, additional correlation rules and topology-aware grouping could be applied.",
      type: "Numerical"
    },
    {
      q: "What are the risks of operating a large network with a single NMS that manages all NEs directly, without an intermediate EMS layer?",
      a: "Without EMS, the NMS must handle: (1) Scale — directly polling thousands of NEs floods the NMS with raw SNMP/NETCONF traffic, creating a single point of performance bottleneck; (2) Vendor heterogeneity — the NMS must implement vendor-specific protocol drivers, MIBs, and YANG models for every NE type, creating maintenance complexity; (3) Alarm volume — unfiltered raw events from all elements simultaneously cause extreme alarm fatigue with no domain-level pre-correlation; (4) Single point of failure — if the NMS is overwhelmed or fails, all visibility is lost across the entire network; (5) Change management — software upgrades to the NMS affect all element management simultaneously, increasing operational risk.",
      type: "Analytical"
    },
    {
      q: "How does an NMS support multi-vendor environments where each vendor uses different management protocols?",
      a: "An NMS supports multi-vendor environments through: (1) EMS abstraction — each vendor's EMS translates vendor-specific protocols (proprietary TL1, SNMP MIBs, NETCONF YANG) into a normalised interface before delivering data to the NMS; (2) Protocol adapters / mediation layer — for NEs without a dedicated EMS, the NMS uses mediation adapters that handle protocol translation internally; (3) Unified data model — the NMS normalises all incoming data into a common information model (e.g., 3GPP IRP, TM Forum SID) regardless of source vendor; (4) Open APIs — the NMS exposes vendor-agnostic REST/JSON NBIs to OSS/BSS, shielding upstream systems from vendor differences; (5) Standards compliance — adoption of NETCONF/YANG with standard YANG modules (IETF, OpenConfig, 3GPP) reduces per-vendor customisation.",
      type: "Conceptual"
    }
  ],
  virtualLab: {
    description: "This lab simulates how the NMS alarm aggregation ratio changes as more EMS domains are added to the managed network. Each domain generates a fixed number of raw alarms, and the NMS correlates approximately 15% of total alarms into root-cause alarms. Adjust domain count and raw alarms per domain to explore the aggregation benefit.",
    interpretation: "As the number of managed EMS domains increases, the total alarm volume grows — but the aggregation ratio remains stable around 1/0.15 ≈ 6.67. This demonstrates that the NMS provides consistent compression regardless of scale, and why hierarchical EMS→NMS management is essential in large multi-domain networks: the EMS pre-filters domain-specific noise, and the NMS applies cross-domain correlation to produce a manageable alert stream for operators.",
    parameters: [
      { id: "domains", name: "EMS Domains", min: 1, max: 10, default: 4, step: 1, unit: "" },
      { id: "rawAlarms", name: "Raw Alarms per Domain", min: 10, max: 200, default: 50, step: 10, unit: "" }
    ],
    generateData: (params) => {
      const maxDomains = params.domains || 4;
      const rawAlarms = params.rawAlarms || 50;
      const pts: Array<{ x: number; y: number }> = [];
      for (let x = 1; x <= maxDomains; x++) {
        const total = x * rawAlarms;
        const correlated = Math.ceil(total * 0.15);
        const ratio = total / correlated;
        pts.push({ x, y: parseFloat(ratio.toFixed(2)) });
      }
      return pts;
    },
    labels: { x: "EMS Domains", y: "Aggregation Ratio" }
  }
};
