import type { TopicData } from './types';

export const topic15Data: TopicData = {
  id: "u4t2",
  title: "Network Observability vs. Monitoring",
  moduleName: "Unit 4: SDN, Network Observability, and Advanced Management",
  context: {
    prerequisites: ["Topic 4.1: SDN Architecture and Controller Engine Functions", "Topic 1.4: Introduction to SNMP (Architecture, Queries, Traps)"],
    dependentTopics: ["Topic 4.3: Data Analytics with AI/ML in Observability", "Topic 4.4: Service Orchestration, Assurance, and Network Slicing (ONAP)"],
    nextSteps: "Apply machine learning analytics to the streamed telemetry data in the next topic."
  },
  storytelling: {
    analogy: "The Doctor's Annual Checkup vs. The ICU Heart Monitor",
    story: "Traditional network monitoring is like going to the doctor once a year. The doctor takes your blood pressure, records it, and says you're fine (SNMP polling every 5 minutes). But if you have a sudden heart attack 10 minutes later, the doctor won't know until next year. Network Observability is like being connected to an ICU heart monitor (Streaming Telemetry). It pushes your heart rate every millisecond. The moment there's a minor anomaly, the monitor sounds an alarm. Monitoring tells you IF a system is down; Observability gives you the deep logs, traces, and metrics to explain WHY it behaved weirdly under load.",
    reflectiveQuestions: ["Why is polling every 5 minutes insufficient to detect CPU spikes that last only 3 seconds?", "How do logs, metrics, and traces complement each other in understanding network state?"],
    technicalConnection: "Network Monitoring (pull-based, like SNMP) tracks device health on a scheduled basis. Network Observability (push-based, like gNMI streaming telemetry) continuously streams operational data (metrics, logs, traces) to a central collector. It allows operators to diagnose complex, transient, and 'unknown-unknown' failures in modern, highly dynamic cloud environments."
  },
  mathModelling: {
    need: "To compare the data overhead generated by pull-based SNMP polling versus push-based streaming telemetry under high-frequency sampling.",
    equation: "D_{ratio} = \\frac{D_{pull}}{D_{push}} = \\frac{S_{req} + S_{resp}}{S_{stream}}",
    technicalDetails: "In SNMP polling (pull), the NMS issues a request (size \\(S_{req}\\)) and receives a response (size \\(S_{resp}\\)). In streaming telemetry (push, e.g. gNMI), a persistent TCP/gRPC stream is established. Once initialized, the device pushes metrics (size \\(S_{stream}\\)) periodically without needing requests. The ratio \\(D_{ratio}\\) shows that pull-based polling carries a request overhead factor. As sampling frequency increases (e.g., streaming every 1 second), the overhead of headers in repeated SNMP GET requests consumes significantly more network resources than a single continuous serialized gRPC push stream.",
    explanation: [
      { term: "D_ratio", meaning: "Bandwidth efficiency ratio of pull vs. push (higher means push is more efficient)." },
      { term: "D_pull", meaning: "Data bandwidth generated by SNMP polling requests and responses." },
      { term: "D_push", meaning: "Data bandwidth generated by streaming telemetry push notifications." },
      { term: "S_req", meaning: "Average SNMP GET request packet size in bytes." },
      { term: "S_resp", meaning: "Average SNMP GET response packet size in bytes." },
      { term: "S_stream", meaning: "Average streaming telemetry push notification size in bytes." }
    ],
    advantages: ["Justifies the transition to gNMI and Prometheus exporter telemetry in ISP networks.", "Assists in sizing telemetry receivers and database collectors."],
    limitations: ["Does not model TCP/gRPC keep-alive and TLS handshake overheads which occur at session startup."],
    simulation: {
      description: "Vary the request/response sizes and stream sizes to observe the data overhead ratio. A higher ratio indicates that polling wastes more bandwidth on requests.",
      parameters: [
        { id: "snmpReqB", name: "SNMP Request Size", min: 64, max: 512, default: 128, step: 16, unit: " B" },
        { id: "snmpRespB", name: "SNMP Response Size", min: 128, max: 1024, default: 256, step: 16, unit: " B" },
        { id: "streamB", name: "Telemetry Stream Size", min: 100, max: 500, default: 150, step: 10, unit: " B" }
      ]
    }
  },
  activities: {
    level1: "Teacher shows a Grafana dashboard displaying real-time CPU utilization telemetry updated every 1 second.",
    level2: "Students identify the Three Pillars of Observability: Metrics, Logs, and Traces.",
    level3: "Class Exercise: Calculate the bandwidth generated by polling 100 routers every 1 second vs streaming telemetry.",
    level4: "Write a comparative review (150 words) on how pull-based Prometheus metrics collection differs from push-based gNMI streaming telemetry."
  },
  projects: {
    scope: "Design a telemetry message structure.",
    objectives: ["Create a JSON/gNMI representation of a streaming interface statistic packet", "Include metrics for input/output octets, error packets, and timestamp in nanoseconds"],
    deliverables: ["JSON telemetry message sample", "1-page system architecture diagram of collector pipeline"]
  },
  questions: [
    { q: "What are the three core data types (the 'three pillars') of Network Observability?", a: "Metrics (numeric telemetry), Logs (textual events), and Traces (end-to-end request journeys).", type: "Conceptual" },
    { q: "Given SNMP GET request = 150 bytes, SNMP response = 350 bytes, and telemetry stream message = 120 bytes, what is the bandwidth efficiency ratio of streaming telemetry over SNMP?", a: "D_ratio = (150 + 350) / 120 = 500 / 120 ≈ 4.17 (meaning SNMP uses 4.17 times more bandwidth than streaming telemetry for the same payload frequency).", type: "Numerical" },
    { q: "What is gNMI and how does it relate to streaming telemetry?", a: "gNMI (gRPC Network Management Interface) is a protocol developed by Google that uses HTTP/2 and Protocol Buffers to stream YANG-modeled telemetry and configuration data in real time.", type: "Conceptual" },
    { q: "Explain the difference between 'known-unknowns' and 'unknown-unknowns' in network diagnostics.", a: "Monitoring is designed for 'known-unknowns' (e.g., we know a link might fail, so we poll its state). Observability is designed for 'unknown-unknowns' (e.g., a bizarre latency spike caused by a weird interaction of microservices), allowing interactive tracing and correlation of unstructured logs and metrics to find the cause.", type: "Analytical" },
    { q: "Why does SNMP polling fail to detect microbursts?", a: "Because SNMP polling intervals are typically long (e.g., 5 minutes). A traffic microburst that spikes link utilization to 100% for 3 seconds and causes packet loss will be averaged out over the 5-minute window and appear as a normal 5% utilization rate.", type: "Analytical" }
  ],
  virtualLab: {
    description: "Streaming Telemetry vs SNMP Polling Simulator. Increase the sampling rate and watch as SNMP polling overhead spikes non-linearly while streaming telemetry remains low and highly efficient.",
    interpretation: "At high frequencies (1-second updates), SNMP polling generates double the packets on the wire (request + response) and carries heavy headers, while streaming telemetry pushes compressed binary data (GPB/gRPC), preserving bandwidth.",
    parameters: [
      { id: "sampleInterval", name: "Update Frequency", min: 1, max: 60, default: 5, unit: "s" }
    ]
  }
};
