import type { TopicData } from './types';

export const topic4Data: TopicData = {
  id: "u1t4",
  title: "Introduction to SNMP (Architecture, Queries, Traps)",
  moduleName: "Unit 1: Introduction to Network Management",
  context: {
    prerequisites: ["Topic 1.3: The FCAPS Process", "UDP Protocol"],
    dependentTopics: ["Topic 1.5: YANG Background & SNMP Limitations", "Topic 2.1: Introduction to Model-Driven Management"],
    nextSteps: "Examine the technical limitations of SNMP when managing massive modern cloud networks in the next topic."
  },
  storytelling: {
    analogy: "The Classroom Quiz vs. Raising a Hand",
    story: "Imagine a teacher (NMS) in a classroom of 30 students (Network Elements). To check if everyone is listening, the teacher can call on each student one by one: 'Are you okay, Alice? Are you okay, Bob?' (This is Polling / Queries using GET/GET-NEXT). But if Alice suddenly feels sick, she doesn't wait for the teacher to ask; she raises her hand and calls out (This is a Trap / Notification). SNMP (Simple Network Management Protocol) works on this dual concept: the NMS periodically polls devices for metrics, but devices can asynchronously send traps to alert the NMS immediately of critical failures.",
    reflectiveQuestions: ["What happens if a student gets sick right after the teacher asks them, and the teacher only polls every 30 minutes?", "Why does the classroom get noisy if the teacher asks questions too frequently?"],
    technicalConnection: "SNMP is a UDP-based master-agent protocol. The NMS queries the SNMP Agent running on switches/routers using GET, GET-NEXT, and SET requests. The Agent replies with responses. For asynchronous events (e.g., interface link down), the Agent sends a Trap to port 162 on the NMS, bypassing the need for immediate polling."
  },
  mathModelling: {
    need: "To calculate the management bandwidth overhead generated by periodic SNMP polling to ensure it does not congest production links.",
    equation: "B_{poll} = \\frac{N \\times S_{packet} \\times 8}{I_{poll}}",
    technicalDetails: "The bandwidth overhead \\(B_{poll}\\) (bits per second) is determined by the number of managed devices \\(N\\), the average size of a complete SNMP query/response transaction \\(S_{packet}\\) in bytes, and the polling interval \\(I_{poll}\\) in seconds. As \\(I_{poll}\\) decreases (faster polling) or \\(N\\) increases, management overhead grows linearly. This helps network administrators strike a balance between fast detection times and acceptable bandwidth utilization (usually < 1% of link capacity).",
    explanation: [
      { term: "B_poll", meaning: "Bandwidth consumed by SNMP polling traffic (bits per second)." },
      { term: "N", meaning: "Number of polled network elements." },
      { term: "S_packet", meaning: "Average size of the request + response packet pair (bytes)." },
      { term: "I_poll", meaning: "Polling interval (seconds)." }
    ],
    advantages: ["Prevents NMS from saturating low-bandwidth WAN links.", "Assists in sizing central NMS network interface cards."],
    limitations: ["Does not account for spontaneous, unpredictable bursts of SNMP Trap messages during widespread network outages."],
    simulation: {
      description: "Adjust the polling interval and device count to see the SNMP management bandwidth consumption. Observe how short intervals quickly consume bandwidth.",
      parameters: [
        { id: "deviceCount", name: "Device Count (N)", min: 50, max: 5000, default: 500, step: 50, unit: " devices" },
        { id: "packetSize", name: "Packet Size (Bytes)", min: 100, max: 1500, default: 300, step: 50, unit: " B" },
        { id: "pollSecs", name: "Polling Interval (I)", min: 5, max: 300, default: 60, step: 5, unit: " s" }
      ]
    }
  },
  activities: {
    level1: "Teacher runs a simple Wireshark capture showing SNMP GetRequest and GetResponse packets on UDP port 161.",
    level2: "Students identify the UDP ports used: 161 for SNMP queries and 162 for SNMP traps.",
    level3: "Class Activity: Draw a timeline diagram comparing the sequence of an SNMP GET query vs an SNMP Trap notification.",
    level4: "Write a comparison (150 words) between UDP and TCP for network management, explaining why SNMP designers chose UDP despite its packet loss risks."
  },
  projects: {
    scope: "Simulate an SNMP manager-agent interaction workflow.",
    objectives: ["Outline packet headers for GET vs TRAP", "Define OID paths for system uptime and interface status", "Draft an SNMP MIB snippet structure"],
    deliverables: ["JSON schema representing SNMP query-response structures", "MIB structure chart"]
  },
  questions: [
    { q: "Which transport protocol and ports does SNMP default to?", a: "UDP, with port 161 for queries (GET/SET) and port 162 for notifications (Traps).", type: "Conceptual" },
    { q: "Calculate the bandwidth overhead of polling 1000 devices every 60 seconds with an average packet pair size of 400 bytes.", a: "B_poll = (1000 * 400 * 8) / 60 = 3,200,000 / 60 ≈ 53,333 bps or 53.3 kbps.", type: "Numerical" },
    { q: "What is the key functional difference between an SNMP query (GET) and an SNMP Trap?", a: "An SNMP query is initiated by the manager (pull model) to fetch current values, whereas an SNMP Trap is initiated asynchronously by the agent (push model) to report an event immediately.", type: "Conceptual" },
    { q: "What is an OID (Object Identifier) in the context of SNMP?", a: "An OID is a dot-separated numeric path (e.g., 1.3.6.1.2.1.1.1) that uniquely identifies a specific managed object in the hierarchical MIB tree database.", type: "Conceptual" },
    { q: "Why is SNMP polling traffic susceptible to packet loss under heavy network congestion?", a: "Because SNMP runs over UDP, which is a connectionless, best-effort transport protocol. It does not retransmit lost packets automatically like TCP.", type: "Analytical" }
  ],
  virtualLab: {
    description: "SNMP Polling Overhead vs Link Utilization Lab. Graph the management traffic overhead relative to overall link bandwidth.",
    interpretation: "For T1 links or slow satellite connections, frequent polling can easily consume a significant percentage of the link, causing queueing delays for customer data. Increasing the polling interval resolves this overhead at the expense of delay in fault discovery.",
    parameters: [
      { id: "linkSpeedKbps", name: "WAN Link Bandwidth (kbps)", min: 64, max: 2048, default: 512, step: 64, unit: " kbps" }
    ]
  }
};
