import type { TopicData } from './types';

export const topic4Data: TopicData = {
  id: "u1t4",
  title: "FCAPS Process",
  moduleName: "Unit I: Introduction to Network Management and Frameworks",
  context: {
    prerequisites: ["EMS and NMS Architecture", "Basic Network Management Concepts"],
    dependentTopics: ["NMS SBI and NBI", "SNMP Concepts & Evolution"],
    nextSteps: "Explore how SNMP implements FCAPS functions at the protocol level, mapping traps to Fault Management and GET/SET operations to Configuration and Performance Management.",
    rfcReferences: [
      { rfc: "ITU-T M.3400", title: "TMN Management Functions", summary: "The authoritative definition of FCAPS (Fault, Configuration, Accounting, Performance, Security) management functions that this topic explains.", url: "https://www.itu.int/rec/T-REC-M.3400/en" },
      { rfc: "ISO/IEC 7498-4", title: "OSI Management Framework", summary: "The ISO standard that introduced the FCAPS framework as the conceptual basis for all network management systems.", url: "https://www.iso.org/standard/14882.html" },
      { rfc: "ITU-T X.700", title: "Management Framework for OSI", summary: "ITU-T version of the OSI management framework defining the five FCAPS functional areas and their relationships.", url: "https://www.itu.int/rec/T-REC-X.700/en" }
    ]
  },
  storytelling: {
    analogy: "Managing a Fleet of Delivery Trucks",
    story: "FCAPS is the ISO framework for network management — think of it as running a professional fleet of delivery trucks. Fault Management is the breakdown service: when a truck stops working, you detect it immediately via GPS tracking, dispatch a repair crew, and log the incident. Configuration Management is the fleet registry: every truck's load capacity, assigned routes, fuel type, and cargo manifest is recorded and kept up to date — no unauthorised modifications allowed. Accounting Management is the billing office: every mile driven, every kilogram carried, and every customer delivery is metered so invoices are accurate and revenue isn't lost. Performance Management is the operations dashboard: average delivery speeds, fuel efficiency per route, and on-time delivery percentages are tracked against KPIs so the fleet manager can identify underperforming drivers or overloaded routes. Security Management is the gated depot: only authorised drivers with valid credentials can start a truck, all cargo is sealed and tamper-evident, and access logs track who entered the depot at what time. Without FCAPS, operating a telecom network is like running a delivery company with no GPS, no vehicle records, no driver logs, and no invoicing system — sheer chaos at scale.",
    reflectiveQuestions: [
      "Which FCAPS function would you use to detect a router interface that keeps cycling between up and down states (link flapping)?",
      "How does Accounting Management in mobile networks (CDR generation) differ from traditional fixed-line billing?",
      "Why is Security Management increasingly critical in modern SDN/NFV environments where the control plane is software-based?"
    ],
    technicalConnection: "ITU-T X.700 (Management Framework) and ITU-T M.3400 (TMN Management Functions) define FCAPS: **Fault Management (ISO 10164-4)**: Alarm surveillance via ITU-T X.733 Event Report Management (alarm states: Outstanding/Acknowledged/Cleared), Probable Cause taxonomy (341 standardized causes from communicationsAlarm to powerProblem), and Event Forwarding Discriminator (EFD) for alarm filtering. Implementation: SNMP Trap (RFC 1215) for push, SNMP GET (RFC 1157) for poll. **Configuration Management (ISO 10164-1)**: ITU-T M.3100 Generic Network Information Model defines Managed Object Classes (MOC): managedElement, equipment, softwareModule, with attributes (administrativeState=locked/unlocked/shuttingDown, operationalState=enabled/disabled). NETCONF (RFC 6241) operations: <edit-config> with target=running datastore, <get-config> for state retrieval. **Accounting Management**: CDR (Call Detail Records per 3GPP TS 32.250-298) generated by P-GW for data sessions, S-CSCF for IMS calls. Fields: subscriberIMSI, startTime, dataVolumeUplink, chargingID. Mediation layer reformats CDRs for billing system ingestion. **Performance Management (ISO 10164-11)**: Counter collection per 3GPP TS 32.401-425 (PM Integration Reference Point). Example counters: RACH.AttConnEstab.Sum (total RACH attempts), HO.SuccOutInterEnbS1 (successful handovers). Collection methods: file-based (SFTP pull of XML/CSV) vs streaming (gRPC gNMI Subscribe). **Security Management (ISO 10164-7)**: AAA via RADIUS (RFC 2865) or Diameter (RFC 6733). Security alarm types per ITU-T X.736: integrityViolation, authenticationFailure, unauthorizedAccessAttempt. Network access control: 802.1X (IEEE) for L2 port authentication, TLS 1.3 (RFC 8446) for management interface encryption."
  },
  mathModelling: {
    need: "An enterprise bank is designing a network SLA for their campus network connecting 5000 employees and 200 ATMs. The IT board has given a budget of $800K/year for network infrastructure and $200K/year for support contracts. They must choose between targeting 99.9% (3-nines), 99.99% (4-nines), or 99.999% (5-nines) availability. Each tier requires different redundancy architectures, fault management tooling, and response time commitments.",
    equation: "DECISION CONSTRAINT: Availability tier determines maximum permissible annual downtime (3-nines=8.76hrs, 4-nines=52.6mins, 5-nines=5.26mins). Support contract must cover MTTR within the chosen tier. Total annual cost must not exceed $1M.",
    technicalDetails: "99.9% (3-nines): Single active-standby router pair, manual failover (<30 min MTTR), standard 8×5 support. Cost: $300K infrastructure + $80K support = $380K/year. Meets budget but 8.76 hrs annual downtime may violate ATM SLA (card schemes require 99.95% uptime). 99.99% (4-nines): Active-active redundant core, automated failover (<2 min MTTR), 24×7 NOC monitoring. Cost: $550K + $150K = $700K/year. 52.6 min annual downtime satisfies ATM card scheme requirements. 99.999% (5-nines): Full dual-path redundancy, SDN-based sub-second failover, dedicated NOC + on-site engineer. Cost: $900K + $250K = $1.15M/year — exceeds budget by 15%.",
    explanation: [
      { term: "99.9% (3-nines)", meaning: "Adopted for internal productivity applications (email, file shares) where brief outages are inconvenient but not business-critical. Fails the ATM SLA requirement. Acceptable for small businesses with no regulatory uptime obligations." },
      { term: "99.99% (4-nines) — Recommended", meaning: "Adopted for financial services, healthcare, and retail networks with regulatory uptime requirements. Meets the ATM card-scheme SLA (99.95% minimum), fits within the $1M budget at $700K/year, and provides 52.6 minutes annual downtime allowance that handles planned maintenance." },
      { term: "99.999% (5-nines)", meaning: "Adopted for mission-critical systems: trading floors, hospital ICUs, emergency services dispatch. Budget-busting for most enterprise deployments. The 15% budget overrun here is not justified by the incremental benefit (47 additional minutes of availability per year) vs 4-nines." }
    ],
    advantages: [
      "4-nines meets the ATM card-scheme regulatory requirement while staying within the $1M budget",
      "Automated failover (<2 min MTTR) at 4-nines tier can be achieved with proven active-active routing technologies (HSRP/VRRP, BFD)",
      "24×7 NOC monitoring at 4-nines tier enables proactive fault detection before SLA breach"
    ],
    limitations: [
      "3-nines is appropriate for SME networks with no regulatory uptime obligation and minimal IT budget",
      "5-nines is adopted when downtime has direct financial liability (stock exchanges, payment processors) where cost of downtime exceeds cost of infrastructure",
      "5-nines is sometimes mandated by regulators (e.g., critical national infrastructure) regardless of cost"
    ]
  },
  activities: {
    level1: "Define each letter in FCAPS — Fault, Configuration, Accounting, Performance, Security Management — and give one concrete real-world example of each from a mobile network operator's daily operations (e.g., which NMS screen or tool is used for each).",
    level2: "Map each FCAPS function to a specific NMS module, tool, or system. For example: Fault → alarm management/ticketing system; Configuration → CMDB and NETCONF provisioning; Accounting → CDR mediation and billing; Performance → KPI dashboard; Security → RBAC and AAA server. Explain the data flow for each mapping.",
    level3: "Calculate network availability for MTBF = 5000 hours and MTTR = 2 hours. Express the answer as a percentage to 4 decimal places. Then determine the maximum MTTR in minutes that would achieve 99.999% availability given MTBF = 5000 hours. Show your algebraic working.",
    level4: "Design a complete FCAPS management plan for a university campus network with 50 access switches, 5 distribution routers, and a 1 Gbps internet uplink. For each FCAPS function, specify: KPIs to monitor, tools to use, escalation procedure, and an automation rule (if applicable)."
  },
  projects: {
    scope: "Design an FCAPS monitoring and management dashboard concept for a hypothetical ISP serving 50,000 broadband subscribers with a mixed fibre and 4G LTE network.",
    objectives: [
      "Define at least 3 measurable KPIs for each FCAPS area and specify target thresholds that would trigger alerts",
      "Propose at least 2 automation rules each for Fault Management (auto-ticketing, auto-rollback) and Configuration Management (change validation, backup scheduling)",
      "Calculate SLA-based availability targets: determine the maximum allowable MTTR for 99.9%, 99.99%, and 99.999% availability given representative MTBF values"
    ],
    deliverables: [
      "FCAPS KPI definition table: 3 KPIs per function with target value, warning threshold, and critical threshold",
      "Automation rule specification document: at least 2 rules per function with trigger condition, action, and rollback procedure",
      "Availability calculation report: MTTR limits for three SLA tiers with supporting calculations and a sensitivity analysis chart"
    ]
  },
  questions: [
    {
      q: "What does each letter in FCAPS stand for, and what is the primary goal of each management function?",
      a: "F — Fault Management: detect, isolate, and resolve network faults rapidly to minimise service downtime. C — Configuration Management: maintain an accurate inventory of all network elements and their configurations; control changes through a structured change management process. A — Accounting Management: collect usage data (CDRs, flow records) to enable accurate billing, quota enforcement, and revenue assurance. P — Performance Management: collect, store, and analyse network KPIs (throughput, latency, error rates, utilisation) to ensure QoS targets are met and to identify degradation before it causes outages. S — Security Management: enforce access control, authentication, authorisation, and audit logging to protect network elements and customer data from unauthorised access or attacks.",
      type: "Conceptual"
    },
    {
      q: "Differentiate between Fault Management and Performance Management — when does a performance issue become a fault?",
      a: "Fault Management deals with discrete, binary events: a network element or service is either working or not. A fault is a condition that directly causes service interruption — a link going down, a process crashing, a hardware failure. Alarms are raised immediately and tracked until resolved. Performance Management deals with continuous, gradual degradation: metrics like latency, packet loss, throughput, and error rates are collected over time and compared against thresholds. A performance issue exists when a metric crosses a warning threshold but service continues. A performance issue becomes a fault when the degradation is severe enough to cause an SLA breach or service interruption — at that point, a fault alarm is generated and Fault Management processes take over. In practice, many faults are first detected by Performance Management (e.g., rising error rate) before the link fully fails.",
      type: "Conceptual"
    },
    {
      q: "Calculate network availability for MTBF = 8000 h and MTTR = 8 h. Then recalculate for MTTR = 1 h.",
      a: "Case 1 (MTTR = 8 h): A = 8000 / (8000 + 8) × 100% = 8000 / 8008 × 100% ≈ 99.9001%. Case 2 (MTTR = 1 h): A = 8000 / (8000 + 1) × 100% = 8000 / 8001 × 100% ≈ 99.9875%. Reducing MTTR from 8 hours to 1 hour improves availability from approximately 99.90% to 99.99%, demonstrating the direct impact of Fault Management efficiency on SLA attainment.",
      type: "Numerical"
    },
    {
      q: "How does Configuration Management prevent fault cascades during network changes?",
      a: "Configuration Management prevents fault cascades through: (1) Change Management Process — all configuration changes must pass a pre-change validation (syntax check, conflict detection) and be approved before execution, preventing misconfiguration-induced faults; (2) CMDB Baseline — the CMDB holds a known-good configuration baseline; automated compliance checks detect drift between running config and baseline, flagging unauthorised changes; (3) Pre-change backup — configurations are automatically backed up before any change, enabling rapid rollback if the change causes a fault; (4) Change windows — changes are scheduled during low-traffic periods with defined rollback criteria; (5) Impact analysis — the CMDB's topology data allows pre-change impact modelling, identifying which services would be affected if a given element is modified. Together these controls ensure that configuration changes, which cause a significant proportion of network outages, are executed safely with full reversibility.",
      type: "Analytical"
    },
    {
      q: "What is the relationship between Accounting Management and QoS policies in a mobile network?",
      a: "Accounting Management and QoS are tightly linked in mobile networks: (1) Usage metering — Accounting collects CDRs (Call Detail Records) and data session records including QoS class, volume, duration, and time-of-day. These feed into both billing and QoS policy decisions; (2) Policy enforcement — in LTE/5G, the PCRF/PCF uses accounting data to enforce data quotas. When a subscriber reaches their data cap, the PCRF instructs the P-GW/UPF to reclassify their traffic to a lower QoS class (throttling); (3) QoS-based charging — different service classes (voice, video, best-effort data) are charged at different rates, requiring the accounting system to track QoS markers per flow; (4) SLA reporting — Accounting data is used to verify that QoS commitments in SLAs (e.g., guaranteed bit rate for enterprise customers) were actually delivered, linking performance metrics to financial accountability.",
      type: "Conceptual"
    }
  ],
  virtualLab: {
    description: "You are a service reliability engineer writing an SLA guarantee. Your task: determine the maximum allowable MTTR to achieve a target availability level (e.g., 99.9%, 99.99%, 99.999%). Adjust the hardware MTBF (how often the device fails) and the MTTR (how long it takes to fix). The chart shows availability as MTTR increases — find the MTTR budget that meets your SLA target before the penalty clause triggers.",
    interpretation: "Reducing MTTR has a disproportionate impact on availability. With MTBF = 2000 h, cutting MTTR from 8 h to 1 h improves availability from 99.60% to 99.95% — an order of magnitude fewer outage minutes per year. To reach 99.999% (five-nines), MTTR must be under 20 minutes at the same MTBF. This demonstrates the value of automated fault detection and pre-configured resolution playbooks: shaving even 1 hour off MTTR can mean millions in SLA penalty avoidance. Use this lab to calculate the MTTR budget your operations team needs to meet a target availability SLA.",
    parameters: [
      { id: "mtbf", name: "MTBF (hrs)", min: 100, max: 10000, default: 2000, step: 100, unit: " hrs" },
      { id: "mttr", name: "MTTR (hrs)", min: 1, max: 100, default: 4, step: 1, unit: " hrs" }
    ],
    generateData: (params) => {
      const mtbf = params.mtbf || 2000;
      const maxMttr = params.mttr || 4;
      const pts: Array<{ x: number; y: number }> = [];
      for (let x = 1; x <= maxMttr; x++) {
        const availability = (mtbf / (mtbf + x)) * 100;
        pts.push({ x, y: parseFloat(availability.toFixed(4)) });
      }
      return pts;
    },
    labels: { x: "MTTR (hrs)", y: "Availability (%)" }
  }
};
